package com.lab.booking.model;

public enum NotificationType {
    FIRST_LOGIN_PASSWORD_CHANGE,
    PASSWORD_RESET,
    RESERVATION_EXPIRED,
    BORROW_OVERDUE,
    ABOUT_TO_EXPIRE_REMINDER,
    OVERDUE_REMINDER,
    PENDING_RESERVATION_APPROVAL,
    PENDING_REPAIR,
    STUDENT_OVERDUE
}
